- README.md
> added new readme

- src/features/header/header.js
- src/features/header/header.module.scss
- src/features/header/index.js
[Issue:](https://github.com/ita-social-projects/what-front/issues/21)
______________________________
__________________________________________________________________________________________________________
Layout, which i have created:
> Header layout is created

- src/features/student-profile/student-profile.js
- src/features/student-profile/student-profile.scss
- Created adaptive version of [student profile](https://github.com/ita-social-projects/what-front/pull/34).
- Removed the row "Group".
Width > 768px:
Width < 768px:
Width < 576px:
> Fixed student profile layout

- src/app.js
- src/features/index.js
- src/features/schedule-student/index.js
- src/features/schedule-student/scheduale.js
- src/features/schedule-student/scheduale.scss
> schedule layout

- package-lock.json
- package.json
> feat: add deploy script

- src/models/lessons/actions.js
- src/models/lessons/index.js
- src/models/lessons/reducer.js
- src/models/lessons/reducers/add-lesson-reducer.js
- src/models/lessons/reducers/all-lessons-reducer.js
- src/models/lessons/reducers/edit-lesson-reducer.js
- src/models/lessons/selectors.js
> Split Lessons Reducer

- src/index.js
Changing for correct router work in a production build
> Replaced BrowserRouter import to HashRouter

- src/components/tabs/tabs.js
- src/features/auth/auth.js
- src/features/counter/counter.js
- src/features/groups/edit-group/edit-group.js
- src/features/groups/group-details/group-details.js
This PR closes #290 
- form reset handler was added;
- changed styles for mentors and students labels;
- changed group details: added students' emails and links to profiles
> Fix group edit

- src/features/modal-window/modal-window.scss
- src/features/students/edit-students-details/edit-students-details.js
By clicking on __Exclude__ button - modal window is being shown. If you confirm your action(excluding) - student will be excluded and system will redirect you to the list of students.
> Modal window for excluding student

- src/features/header/header.scss
**Header for administrator** 
> **1024** px:
> **1366**px: 
**Header for secretary** 
>**1024**px:
>**1366**px:
**Header for mentor**
>**1024**px:
>**1366**px:
> Fix header component styles

- src/features/lessons/add-lesson/add-lesson.js
- src/features/lessons/edit-lesson/edit-lesson.js
- src/shared/api-service/config.js
> Fix Student Ids

- src/features/groups/group-details/group-details.js
- src/features/mentors/edit-mentor/edit-mentor.js
- src/features/students/student-details/student-details.js
I have added links for 
- groups in Student Details
- mentors in Group Details
- course in Group Details
> Add links in details components

- src/features/header/header.js
- The same active tab after page reloading
https://user-images.githubusercontent.com/55295369/103218116-d9662d80-4922-11eb-8e10-f4332539fae3.mp4
> Fix header active tabs

- src/screens/groups/groups-tabs.js
> Fixed active mentors in group details

- src/features/header/header.js
1. I have adde Link instead of `<a></a>` in order to prevent browser page refresh
2. Removed unused variables
> Fix header

- src/features/lessons/add-lesson/add-lesson.js
- src/features/lessons/add-lesson/add-lesson.scss
- src/features/lessons/edit-lesson/edit-lesson.js
- src/features/lessons/edit-lesson/edit-lesson.scss
- User can not choose future date.
- Add scroll to class register.
- Add Mentors Names for datalist
> Fix Add/Edit Lesson

- src/features/auth/auth.js
- src/features/groups/list-of-groups/list-of-groups.js
- src/features/groups/list-of-groups/list-of-groups.scss
- src/features/lessons/list-of-lessons/list-of-lessons.js
- src/features/lessons/list-of-lessons/list-of-lessons.scss
1. I have added sorting for lessons and groups by start date
2. I have reversed date on cards in list of groups
> Sorting for lessons and groups

- src/features/layout/layout.js
404 page renders if path equals '/'
This pr closes #347 
'/' path redirects to homepage of current user (depending on user's role)
> Fix homepage redirecting

- src/features/layout/layout.js
Mentors have not access to unassigned list component
> Fix mentors unassigned list

- src/features/my-profile/my-profile.js
- src/features/my-profile/my-profile.scss
- src/models/account/sagas.js
Fixed problem of rendering My profile feature.
Now any user can see personal details by clicking on the My profile icon.
This PR
close #336
> Fix my profile

- src/features/header/header.js
> Fixed header tabs

- src/components/card/card.js
- src/components/card/card.scss
- src/features/courses/list-of-courses/list-of-courses.js
- src/features/courses/list-of-courses/list-of-courses.scss
- src/features/groups/list-of-groups/list-of-groups.js
- src/features/groups/list-of-groups/list-of-groups.scss
- src/features/lessons/list-of-lessons/list-of-lessons.js
- src/features/lessons/list-of-lessons/list-of-lessons.scss
- src/features/mentors/list-of-mentors/list-of-mentors.js
- src/features/secretaries/list-of-secretaries/list-of-secretaries.js
- src/features/students/list-of-students/list-of-students.js
- src/styles/_helpers.scss
List of mentors
List of secretaries
List of lessons
List of groups
List of courses
> Fixed styles

- src/features/groups/list-of-groups/list-of-groups.js
- src/features/lessons/list-of-lessons/list-of-lessons.js
If we try to find the group by name or by date and there are no groups:
> Updated list of groups

- src/components/pagination/pagination.js
- src/components/pagination/pagination.scss
- src/features/courses/list-of-courses/list-of-courses.js
- src/features/groups/list-of-groups/list-of-groups.js
- src/features/lessons/list-of-lessons/list-of-lessons.js
- src/features/mentors/list-of-mentors/list-of-mentors.js
- src/features/secretaries/list-of-secretaries/list-of-secretaries.js
- src/features/students/list-of-students/list-of-students.js
> Updated pagination component

- src/features/mentors/edit-mentor/edit-mentor.js
- src/features/mentors/mentor-details/mentor-details.js
- General downloading of courses and groups in mentor details feature fixed
- Mentor details extended
> Mentor details extended

- src/features/lessons/edit-lesson/edit-lesson.js
- src/features/lessons/lesson-details/lesson-details.js
We fetch all students and mentors(active and not active) for lessons.
> fixed students and mentors data

- src/features/courses/course-details/course-details.js
- src/features/groups/edit-group/edit-group.js
- src/features/groups/group-details/group-details.js
- src/features/lessons/edit-lesson/edit-lesson.js
- src/features/mentors/edit-mentor/edit-mentor.js
- src/features/mentors/mentor-details/mentor-details.js
- src/features/students/edit-students-details/edit-students-details.js
- src/features/students/student-details/student-details.js
> FIxed loaders

- src/features/lessons/add-lesson/add-lesson.js
- src/features/lessons/edit-lesson/edit-lesson.js
- src/features/validation/validation-helpers.js
- Password: 
-min 8 characters
-min one lowercase letter
-min one uppercase letter
-ony Latin lettersr
- SRS:
-update information
- Additional :
-changed import `validationSheme` from `validation-helpers.js` in` **edit-lesson**`
-changed` themeNameValidation` in `lessonValidation`
- SRS:
-updated information
> Validation fix

- src/components/card/card.scss
- src/components/search/search.scss
- src/components/tab/tab.scss
- src/features/change-password/change-password.scss
- src/features/counter/button.scss
- src/features/lessons/add-lesson/add-lesson.scss
- src/features/lessons/edit-lesson/edit-lesson.scss
- src/features/lessons/lesson-details/lesson-details.scss
- src/features/mentors/edit-mentor/edit-mentor.scss
- src/features/modal-window/modal-window.scss
- src/features/my-profile/my-profile.scss
- src/features/registration/registration.scss
- src/features/schedule/schedule.scss
- src/features/students/edit-students-details/edit-students-details.scss
- src/features/unassigned-list/unassigned-list.scss
- src/styles/_color-palette.scss
- src/styles/_fonts.scss
- src/styles/_helpers.scss
- src/styles/_sizes.scss
- src/styles/_theme.scss
- src/styles/_variables.scss
- Changed main theme colors to brand new ones
- Changed fonts to brand new one
`font-family: 'Poppins', sans-serif;`
- Changed page mixin and set it new box-shadow and border radius to 3px;
- Fixed components that uses unreachable variables, maps or mixins
> Changing values of variables

- src/features/mentors/list-of-mentors/list-of-mentors.js
- src/features/secretaries/list-of-secretaries/list-of-secretaries.js
- src/features/students/list-of-students/list-of-students.js
Default sorting by last name to the list of students, mentors and secretaries added
> Default sorting by last name

- src/features/students/student-details/student-details.js
- src/features/validation/validation-helpers.js
- src/shared/api-service/config.js
1. Fixed auth validation
2. changed BASE URL
3. fixed loader in student details
> Minor fixes

- config/paths.js
- config/webpack.prod.js
- package-lock.json
- package.json
Production build optimization: enabled [PurgeCSS](https://purgecss.com/) to remove unused styles (such as unused bootstrap classes).
```
Before -> After
171 Kb -> 23 Kb
```
> feat: set css treeshacking

- src/features/courses/course-details/course-details.js
- src/models/courses/actions.js
- src/shared/api-service/config.js
- src/shared/api-service/interceptors.js
- crash when receive 500 server error
- invalid courses error
- added default error when error format isn't proper
> Fix error interceptor

- src/features/change-password/change-password.js
- src/models/account/reducers/change-password.js
- src/models/account/sagas.js
- fixed change password model
- added model window to confirm the change password
- added loader to the form
- redirect the user to my profile feature if the password has been successfully changed
- added alerts
This PR
close #366
> Update change password feature

- src/features/not-found/not-found.js
- src/features/not-found/not-found.scss
> feat: redesign 404 error

- src/features/registration/registration.js
- src/features/registration/registration.scss
- src/features/registration/successful-registration-alert.js
- changed link color according to main color of new design theme
- changed button color of 'submit registration' btn
- changed btn color of modal window button
this pr closes #482
> WIP : Redesign registration component

- src/features/courses/list-of-courses/list-of-courses.js
- src/features/courses/list-of-courses/list-of-courses.scss
> Redesign list of courses

- src/components/tab/tab.scss
- src/components/tabs/tabs.js
- src/styles/_helpers.scss
- changed bg color of active tab
- changed text color of tabs
- changed border radius of tabs
- removed `back` button
> Redesign tabs

- src/features/change-password/change-password.js
- src/features/change-password/change-password.scss
- src/features/mentors/edit-mentor/edit-mentor.js
- src/features/my-profile/my-profile.js
- src/features/my-profile/my-profile.scss
- src/features/secretaries/edit-secretarys-details/edit-secretarys-details.js
- changed buttons colors
This PR
closes #496
> Redesign change password

- src/features/auth/auth.js
- src/features/registration/registration.js
Removed default error from browser about email error:
> Fix authorisation and registration

- src/features/groups/list-of-groups/list-of-groups.js
- src/models/courses/actions.js
- Changed sorting from single-page sorting to all-pages sorting
- Added finish date column
- Added sorting to finish date column
this pr closes #518
> fix list of groups component

- src/features/header/header.js
- src/features/header/header.scss
- added animation and rotation to the triangle icon after opening the menu 
- added borders to the menu to highlight the menu
this pr closes #515
> fix header dropdown

- src/features/courses/list-of-courses/list-of-courses.js
- src/models/courses/actions.js
> fix sorting and course pagination

- src/features/sidebar/sidebar.js
- src/features/sidebar/sidebar.scss
Fix a bug where the sidebar link's text is visible under the icons.
> Fixed animation of sidebar

- src/features/change-password/change-password.js
- src/features/modal-window/modal-window.js
- src/features/modal-window/modal-window.scss
- src/features/validation/validation-helpers.js
- fixed change password validation
- changed route after a successful request. After successfully changed the password  the user go back to the previous page
- added margins to the modal window
This PR
close #501
> Fix change password

- src/features/students/student-details/student-details.js
Fixed [Bug report](https://github.com/ita-social-projects/what-front/issues/436)
> Fix: 404 is not shown on invalid student ID

- src/features/groups/edit-group/edit-group.js
- Fixed disabled buttons when student/mentor  added/removed
> Fix disabled buttons in groups/edit

- src/features/sidebar/sidebar.js
- src/shared/api-service/api-service.js
> Fix: active sidebar item is not shown on Roles page

- src/features/courses/edit-course/edit-course.js
- src/features/mentors/edit-mentor/edit-mentor.js
- src/features/secretaries/edit-secretarys-details/edit-secretarys-details.js
- src/features/students/edit-students-details/edit-students-details.js
- src/models/courses/actions.js
- src/models/secretary/actions.js
- src/models/secretary/reducers/delete-secretary-reducer.js
- src/models/students/actions.js
- src/models/students/reducers/remove-student-reducer.js
Change color and text of button "delete" in modal window
- changed colors and content of remove buttons
- fixed bugs with extra alerts after removing error
> Changed colors of modal window buttons

- src/features/courses/edit-course/edit-course.js
- src/features/courses/edit-course/edit-course.scss
- src/features/groups/edit-group/edit-group.js
- src/features/groups/edit-group/edit-groups.scss
- src/features/mentors/edit-mentor/edit-mentor.js
- src/features/mentors/edit-mentor/edit-mentor.scss
- src/features/students/edit-students-details/edit-students-details.js
- Changed colors of buttons according to color palette (theme-colorAccent, Dark , Light, Medium) 
this pr closes #524 
I will not attach a screenshot , because the colors are visually almost unchanged ( they looks similar . Info and color Accent, for ex.)
>  change colors according to color palette

- src/features/header/header.js
- fixed links in the dropdown menu. Now it's whole clickable link. Not only text-area in menu-item
this pr closes #531
> fix account dropdown

- src/features/groups/download-groups/download-groups.js
- src/features/groups/download-groups/download-groups.scss
- src/features/groups/download-groups/index.js
- src/features/groups/list-of-groups/list-of-groups.js
- src/features/layout/layout.js
- src/shared/routes/paths.js
Changed and fixed import of groups
> import of groups added

- src/shared/routes/paths.js
> Bychkov 588 invalid student redirection

- src/features/secretaries/list-of-secretaries/list-of-secretaries.js
[Secretaries page] During loading of secretaries - total quantity of secretaries is diplayed for the user(Admin and Secretary roles) #584
fix bug
> fix:Secretary-page-loading

- src/components/tabs/tabs.js
- src/features/secretaries/list-of-secretaries/list-of-secretaries.js
Fix format in
list-of-secretaries.js
tabs.js
and misprint in
tabs.js
> fix-format:Misprint-and-reformation-problems

- src/features/validation/validation-helpers.js
> fix: actual regex for password validation

- src/features/courses/add-course/add-course.js
- src/features/groups/start-group/start-group.js
> fix: loader on start new group and add new course

- src/features/schedule/schedule-base/schedule.js
- src/utils/helpers/date.js
- src/utils/helpers/index.js
- src/utils/index.js
Fix clicking button 'today' in 'schedule'
issue: https://github.com/ita-social-projects/what-front/issues/580
> fix no result clicking today

- README.md
Add photos of developers in README.md
issue: https://github.com/ita-social-projects/what-front/issues/617
> doc: add photos of developers in README.md

- src/features/groups/list-of-groups/list-of-groups.js
- src/features/groups/list-of-groups/list-of-groups.scss
- src/features/lessons/list-of-lessons/list-of-lessons.js
- src/features/lessons/list-of-lessons/list-of-lessons.scss
- src/features/students/list-of-students/list-of-students.js
- src/features/students/list-of-students/list-of-students.scss
fix #616 and grid's row columns proportions in students tab are now unified with groups tab
https://user-images.githubusercontent.com/64030284/120697825-dd404200-c4b6-11eb-8993-62d494ae39df.mp4
columns proportions:
> Bychkov 616 sticked buttons in studetns and lessons tabs

- src/features/auth/auth.js
Task issue - [#607](https://github.com/ita-social-projects/what-front/issues/607)
Added trim() for email field in auth page.
https://user-images.githubusercontent.com/42357921/121131249-2c300380-c838-11eb-95b5-454a508ba1f4.mp4
> Kryoka #607 spaces in email field

- src/features/groups/group-details/group-details.js
- src/utils/helpers/common-helpers.js
commonHelper.transformDateTime corrected - common render format DD-MM-YYYY was changed to DD.MM.YYYY
> commonHelper.transformDateTime corrected

- src/features/students/list-of-students/list-of-students.js
Add block view.
Close #577 
- added function for block visibility
- added new state list/block visibilty
- changed markup
- updated srs
PS: block view added only for list-of-students cause I'll refactor and simplify code in next sprint - [issue 639](https://github.com/ita-social-projects/what-front/issues/639).
PSS: also need to edit design in Figma
https://user-images.githubusercontent.com/42357921/121688974-bee8d080-cacc-11eb-99bb-8dca36f65b96.mp4
> Kryoka 577 blocks view

- src/features/lessons/student-lesson-details/__tests__/student-lesson-details.test.js
- src/features/lessons/student-lesson-details/student-lesson-details.js
Close #649 
100% covered with unit tests studentLessonDetails component
> unit tests for studentLessonDetails component

- src/components/table/index.js
- src/components/table/table.js
- src/components/table/table.scss
- src/features/courses/list-of-courses/list-of-courses.js
- src/features/courses/list-of-courses/list-of-courses.scss
- src/features/groups/list-of-groups/list-of-groups.js
- src/features/groups/list-of-groups/list-of-groups.scss
- src/features/lessons/list-of-lessons/list-of-lessons.js
- src/features/lessons/list-of-lessons/list-of-lessons.scss
- src/features/mentors/list-of-mentors/list-of-mentors.js
- src/features/mentors/list-of-mentors/list-of-mentors.scss
- src/features/secretaries/list-of-secretaries/list-of-secretaries.js
- src/features/secretaries/list-of-secretaries/list-of-secretaries.scss
- src/features/students/list-of-students/list-of-students.js
- src/features/students/list-of-students/list-of-students.scss
- src/features/unassigned-list/unassigned-list.js
- src/features/unassigned-list/unassigned-list.scss
Closed #563  
Closed #506 
make file for table of list`s with own sorting as validation
delete indexes in components mentors, secretaries, students, lessons, groups, courses
Video about creating table component with own sorting func
https://user-images.githubusercontent.com/82518924/122241605-5bdfab00-cecb-11eb-9cc7-a8ae8d2f8f03.mp4
Video about deleting index from list and blocks
https://user-images.githubusercontent.com/82518924/122241858-8b8eb300-cecb-11eb-955d-908fd41c8156.mp4
> Mezentsev 563 506 Refactoring: Table component for lists and fixed index

- package-lock.json
Issue: https://github.com/ita-social-projects/what-front/issues/654
Summary of Issue:
====
Restoring package-lock.json which was mistakenly removed.
> fix: restoring package-lock.json

- src/components/blocks/blocks.js
- src/components/blocks/index.js
- src/components/list/index.js
- src/components/list/list.js
- src/components/list/list.scss
- src/components/rows/index.js
- src/components/rows/rows.js
- src/components/table/table.js
- src/features/courses/list-of-courses/list-of-courses.js
- src/features/groups/list-of-groups/list-of-groups.js
- src/features/lessons/list-of-lessons/list-of-lessons.js
- src/features/mentors/list-of-mentors/list-of-mentors.js
- src/features/secretaries/list-of-secretaries/list-of-secretaries.js
- src/features/students/list-of-students/list-of-students.js
- src/features/students/list-of-students/list-of-students.scss
- src/features/unassigned-list/unassigned-list.js
Close #639
Close #562 
- Created new components: List, Rows, Blocks
- Added correct using of new component Table with List in all list-of-... components
- Refactored a lot
I do not attach screenshots or videos. I ask you to run it locally and check.
> Kryoka 639 refactor get rows and get blocks

- src/features/mentors/edit-mentor/edit-mentor.js
fix component
https://user-images.githubusercontent.com/30880200/123157817-ad5fdb00-d473-11eb-8286-b943a0c82deb.mp4
> fix:Edit-mentor-doesnt-preload-mentor-data

- src/features/layout/layout.js
> #670 Redirect from lesson-list page to add-lesson leads to page 404 

- src/features/groups/list-of-groups/list-of-groups.js
- src/utils/helpers/common-helpers.js
fix #387 
by date (make two inputs: start and end date):
- by default start date is the first day of current year
- by default end date is current date
https://user-images.githubusercontent.com/64030284/122099987-532f9c00-ce1b-11eb-9904-510b46d85c36.mp4
> Bychkov 387 sort group

- src/components/double-date-filter/doubleDateFilter.js
- src/components/double-date-filter/index.js
- src/components/index.js
- src/features/groups/list-of-groups/list-of-groups.js
- src/features/lessons/list-of-lessons/list-of-lessons.js
- src/utils/helpers/common-helpers.js
fix #653 
- added doubleDateFilter component to common components
- replaced plain filters with doubleDateFilter component in lesson-list and groups-list
- lesson-list and groups-list components' refactor
> Bychkov 653 filter input refactor

- src/features/lessons/add-lesson/__tests__/add-lesson.test.js
- src/features/lessons/edit-lesson/__tests__/edit-lesson.test.js
- src/features/lessons/edit-lesson/__tests__/mocks/mock-data.js
- src/features/lessons/edit-lesson/edit-lesson.js
- src/models/lessons/__mocks__/index.js
- src/models/lessons/__mocks__/lessons-mock-data.js
- src/models/lessons/__mocks__/lessons.js
- src/models/lessons/index.js
What has been done:
1. Unit tests for edit-lesson component 
2. Mock selectors for Lessons Model (allLessons, studentLessons, addLesson, editLesson)
Coverage
> Yakymova #680 unit tests edit lesson

- src/features/mentors/mentor-details/__tests__/mentor-details.test.js
- src/features/mentors/mentor-details/__tests__/mocks/mock-data.js
- src/features/mentors/mentor-details/mentor-details.js
> Bychkov 693 unit test for mentor details

- src/features/students/student-details/__tests__/mock-data.js
- src/features/students/student-details/__tests__/student-detals.test.js
- src/features/students/student-details/student-details.js
> feat: unit test is done

- src/shared/api-service/config.js
> fix(http): change the base URL in the axios config

- src/features/auth/auth.js
> Resolves #719, changed incorrect name of link 'Forgot Password'

- src/models/courses/actions.js
> fix(courses): course does not display after saving

- src/features/lessons/edit-lesson/edit-lesson.js
- src/features/validation/validation-helpers.js
> Resolves #714 Fixed edit lessons details page save button work

- src/features/schedule/schedule-base/schedule.js
- src/models/schedules/actions.js
> changed path to database

- src/features/courses/list-of-courses/list-of-courses.js
- src/features/groups/list-of-groups/list-of-groups.js
- src/features/mentors/list-of-mentors/list-of-mentors.js
- src/features/secretaries/list-of-secretaries/list-of-secretaries.js
- src/features/students/list-of-students/list-of-students.js
> Matvienko 752 Pagination is shown when the entire list is displayed on the page

- src/features/courses/edit-course/__tests__/edit-course.test.js
> Resolve #681, added unit-tests for edit course component

- src/features/secretaries/edit-secretarys-details/__mocks__/mockedData.js
- src/features/secretaries/edit-secretarys-details/__tests__/edit-secretarys-details.test.js
> Resolve #678 added unit-tests for edit-secretaries-details component

- package.json
- src/features/students/edit-students-details/__tests__/edit-students-details.test.js
- src/features/students/edit-students-details/__tests__/mock-data.js
> Zenin #679

- src/features/validation/validation-helpers.js
> Matvienko 716 ['Edit student details' page] Incorrect error message is displayed in the last name field

- src/features/students/list-of-students/list-of-students.js
> #786 fix layout with buttons upload and add students

- src/components/table/table.js
- src/components/table/table.scss
[Assignment] The table's content is broken
> fix table word break

- src/features/unassigned-list/unassigned-list.js
- src/features/unassigned-list/unassigned-list.scss
> resolves #814 fixed user details markup in unassigned users list

- src/features/validation/validation-helpers.js
> updated validation scheme for lesson

- src/components/blocks/blocks.js
- src/components/blocks/blocks.scss
> ['courses' page] 'Details' button isn't displayed on course cards #787

- src/features/sidebar/__tests__/__snapshots__/sidebar.test.js.snap
- src/features/sidebar/__tests__/sidebar.test.js
> Matvienko 785 create unit tests for sidebar component

- src/shared/api-service/interceptors.js
https://user-images.githubusercontent.com/13970319/152344627-f059641c-e671-46c1-8970-e83fb467c0a7.png
> List of lessons for user(mentor) is loaded

- src/features/unassigned-list/unassigned-list.js
https://user-images.githubusercontent.com/13970319/151719256-f177967c-8d14-4a5a-b63d-6ff2c9e7fdbb.png
> [Unassigned users] searching by name is displayed existing unassigned user in table

- src/features/secretaries/list-of-secretaries/list-of-secretaries.js
https://user-images.githubusercontent.com/13970319/151718868-9478e214-e298-4c5e-8869-05be8d10b0fd.png
> searching by name is  displayed existing secretaries in table

- src/features/courses/list-of-courses/__tests__/list-of-courses.test.js
- src/features/courses/list-of-courses/__tests__/mocks/mock-data.js
- src/features/courses/list-of-courses/list-of-courses.js
add unit tests for list of courses component
> 872 add unit tests for list of courses component

- src/features/courses/list-of-courses/list-of-courses.js
1. Fixed warnings from eslint(1 problem with controlling input labels is left);
2. Removed unnecessary state expressions;
3. Refactored useEffect logic and Api calls;
4. Refactored conditions (if  and "&&" statements) for components rendering;
5. Removed pagination statements and functions from component;
6. Changed handler for input searching
7. Result: component list-of-courses rerenders 5 times on first visiting and 4 times on disabled switch click, changed count of code lines from 382 to 258;
> [Courses List] refactor list-of-courses-feature

- src/features/lessons/edit-lesson/edit-lesson.js
- src/features/validation/validation-helpers.js
Problem:
- the table with students is not displayed
Solution: 
- fixed useEffect thanks to that we will first load data with lessons and students, then send a request to get information about a specific group whose lesson we have opened. And only after the successful execution of this request, we process the received data and get an array of students in this group
- fixed onSubmit to coorect prepare information for edit lesson data.
> [EditLesson] The table with students is not displayed

- src/features/layout/layout.js
- src/features/schedule/add-schedule/add-schedule-useFetch.js
problem: When a user makes action by the button "Add schedule" occur error "This page is missing" #844
solution: Added new route to layout.js and changed parametres of useActions in add-schedule-useFetch.js
> [Schedule] When a user makes action by the button "Add schedule" occur error "This page is missing" #844

- src/features/unassigned-list/unassigned-list.js
> [Students Page] Fixed adding a student functional for Secretary and Admin #897

- src/shared/api-service/config.js
944. Change route to new back-end
> 944. Change route to new back-end

- src/features/mentors/list-of-mentors/useFetchMentors.js
change route. But it is not good solving of this problem. It need to import from config
> fix: change route for list of mentors route
